{
 "title": "MyTomorrows Flask Metrics",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "namespace", "query": { "query": "label_values(namespace)" } },
   {
    "name": "pod",
    "query": {
     "query": "label_values(kube_pod_info{namespace=\"$namespace\"}, pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Requests per second",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 10, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(flask_http_request_duration_seconds_count{status=\"200\", namespace=\"$namespace\", pod=~\"$pod\"}[30s])",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "Errors per second",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 6, "x": 10, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(flask_http_request_duration_seconds_count{status!=\"200\",namespace=~\"$namespace\", pod=~\"$pod\"}[30s]))",
     "legendFormat": "errors"
    }
   ]
  },
  {
   "title": "Total requests per minute",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(flask_http_request_total[1m])",
     "legendFormat": "HTTP {{ status }}"
    }
   ]
  },
  {
   "title": "Average response time [30s]",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(flask_http_request_duration_seconds_sum{status=\"200\", namespace=~\"$namespace\", pod=~\"$pod\"}[30s])\n/\nrate(flask_http_request_duration_seconds_count{status=\"200\", namespace=~\"$namespace\", pod=~\"$pod\"}[30s])",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "Request duration [s] - p50",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 10, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, rate(flask_http_request_duration_seconds_bucket{status=\"200\",namespace=~\"$namespace\", pod=~\"$pod\"}[30s]))",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by (pod, namespace) (\n  avg_over_time(container_memory_usage_bytes{namespace=~\"$namespace\", pod=~\"$pod\"}[5m]))\n",
     "legendFormat": "{{namespace}} - {{pod}}"
    }
   ]
  },
  {
   "title": "Requests under 250ms",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 10, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "increase(flask_http_request_duration_seconds_bucket{status=\"200\",le=\"0.25\",namespace=~\"$namespace\", pod=~\"$pod\"}[30s]) \n/ ignoring (le) increase(flask_http_request_duration_seconds_count{status=\"200\",namespace=~\"$namespace\", pod=~\"$pod\"}[30s])",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "Request duration [s] - p90",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 9, "x": 10, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.9, rate(flask_http_request_duration_seconds_bucket{status=\"200\",namespace=~\"$namespace\", pod=~\"$pod\"}[30s]))",
     "legendFormat": "{{ path }}"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{namespace=~\"$namespace\",pod=~\"$pod\"}[30s])",
     "legendFormat": "{{namespace}} - {{pod}}"
    }
   ]
  }
 ]
}