image:
  repository: 195275637740.dkr.ecr.eu-central-1.amazonaws.com/mytomorrows
  tag: latest
  pullPolicy: IfNotPresent

#Port Flask runs on and Container is exposed on
global:
  myTomAppPort: 8081
  replicas: 2

ingress:
  enabled: false

service:
  type: ClusterIP

configMap:
  ENVIRONMENT: test
  API_BASE_URL: "http://localhost"
  LOG_LEVEL: DEBUG
  MAX_CONNECTIONS: 100

secrets:
  SECRET_KEY: 'myTom123$123'
  DB_PASSWORD: 'myTomDB456'