apiVersion: v1
kind: Service
metadata:
  name: {{ include "mytomapp.fullname" . }}
  labels:
    app: {{ include "mytomapp.name" . }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.global.myTomAppPort }}
      targetPort: {{ .Values.global.myTomAppPort }}
      protocol: TCP
      name: http
  selector:
    app: {{ include "mytomapp.name" . }}

